import 'package:flutter/material.dart';

class HSRCH {
  final String namecharacters,imgcharacters, combatypesimg, combatypesname, Factions, pathcharactersimg, pathcharactersname,
  upgradematerials1img, upgradematerials2img, upgradematerials3img, upgradematerials4img,
  upgradematerials1name, upgradematerials2name, upgradematerials3name, upgradematerials4name,
  basicatkicon, basicatkname, basicatkdetail,
  skillicon, skillname, skilldetail,
  ultimateicon, ultimatename, ultimatedetail,
  talenticon, talentname, talentdetail, techniqueicon, techniquename, techniquedetail,
  eidolon1icon, eidolon2icon, eidolon3icon, eidolon4icon, eidolon5icon, eidolon6icon,
  eidolon1name, eidolon2name, eidolon3name, eidolon4name, eidolon5name, eidolon6name,
  eidolon1detail, eidolon2detail, eidolon3detail, eidolon4detail, eidolon5detail, eidolon6detail,
  totalStats1, totalStats2, totalStats3,
  ascension2icon, ascension4icon, ascension6icon,
  ascension2name, ascension4name, ascension6name,
  ascension2detail, ascension4detail, ascension6detail;
  final int id, hpcharacters, atkcharacters, defcharacters, speedcharacters, tauntcharacters,charactersRarity;
  final Color color;

  HSRCH(
      {required this.id,
      required this.namecharacters,
      required this.charactersRarity,
      required this.imgcharacters,
      required this.combatypesimg,
      required this.combatypesname,
      required this.Factions,
      required this.pathcharactersimg,
      required this.pathcharactersname,
      required this.upgradematerials1img,
      required this.upgradematerials2img,
      required this.upgradematerials3img,
      required this.upgradematerials4img,
      required this.upgradematerials1name,
      required this.upgradematerials2name,
      required this.upgradematerials3name,
      required this.upgradematerials4name,
      required this.basicatkicon,
      required this.basicatkname,
      required this.basicatkdetail,
      required this.skillicon,
      required this.skillname,
      required this.skilldetail,
      required this.ultimateicon,
      required this.ultimatename,
      required this.ultimatedetail,
      required this.talenticon,
      required this.talentname,
      required this.talentdetail,
      required this.techniqueicon,
      required this.techniquename,
      required this.techniquedetail,
      required this.eidolon1icon,
      required this.eidolon2icon,
      required this.eidolon3icon,
      required this.eidolon4icon,
      required this.eidolon5icon,
      required this.eidolon6icon,
      required this.eidolon1name,
      required this.eidolon2name,
      required this.eidolon3name,
      required this.eidolon4name,
      required this.eidolon5name,
      required this.eidolon6name,
      required this.eidolon1detail,
      required this.eidolon2detail,
      required this.eidolon3detail,
      required this.eidolon4detail,
      required this.eidolon5detail,
      required this.eidolon6detail,
      required this.totalStats1,
      required this.totalStats2,
      required this.totalStats3,
      required this.ascension2icon,
      required this.ascension4icon,
      required this.ascension6icon,
      required this.ascension2name,
      required this.ascension4name,
      required this.ascension6name,
      required this.ascension2detail,
      required this.ascension4detail,
      required this.ascension6detail, 
      required this.atkcharacters,
      required this.hpcharacters,
      required this.defcharacters,
      required this.speedcharacters,
      required this.tauntcharacters,
      required this.color,
});
}

List<HSRCH> mc = [
  //1
   HSRCH(
      id: 1,
      namecharacters: "Imbibitor Lunae",
      charactersRarity: 5,
      imgcharacters: "imagecharacters/Dan Heng - Imbibitor Lunae.png",
      combatypesimg: "icongame/imaginary.png",
      combatypesname: "Imaginary",
      pathcharactersimg: "icongame/the_destruction_sm.png",
      pathcharactersname: "Destruction",
      Factions: "	Xianzhou: The Luofu",
      upgradematerials1img: "imageUpgradeMaterials/Immortal Scionette.png",
      upgradematerials2img: "imageUpgradeMaterials/RegretofInfiniteOchema.png",
      upgradematerials3img: "imageUpgradeMaterials/Shattered Blade.png",
      upgradematerials4img: "imageUpgradeMaterials/Suppressing Edict.png",
      upgradematerials1name: "Immortal Scionette",
      upgradematerials2name: "Regret of Infinite Ochema",
      upgradematerials3name: "Shattered Blade",
      upgradematerials4name: "Suppressing Edict",
      basicatkicon: "imageSkills/ImbibitorLunaeBasicATK.png",
      basicatkname: "Beneficent Lotus",
      basicatkdetail: "Single Target Uses a 2-hit attack and deals Imaginary DMG equal to 50% of Dan Heng - Imbibitor Lunae's ATK to a single enemy target. Single Target Uses a 3-hit attack and deals Imaginary DMG equal to 130% of Dan Heng - Imbibitor Lunae's ATK to a single enemy target. Blast Uses a 5-hit attack and deals Imaginary DMG equal to 190% of Dan Heng - Imbibitor Lunae's ATK to a single enemy target. From the fourth hit onward, simultaneously deals Imaginary DMG equal to 30% of Dan Heng - Imbibitor Lunae's ATK to adjacent targets. Blast Uses a 7-hit attack and deals Imaginary DMG equal to 250% of Dan Heng - Imbibitor Lunae's ATK to a single enemy target. From the fourth hit onward, simultaneously deal Imaginary DMG equal to 90% of Dan Heng - Imbibitor Lunae's ATK to adjacent targets.",
      skillicon: "imageSkills/ImbibitorLunaeSkill.png",
      skillname: "Dracore Libre",
      skilldetail: "Enhances Basic ATK. Enhancements may be applied up to 3 times consecutively. Using this ability does not consume Skill Points and is not considered as using a Skill.Enhanced once, Beneficent Lotus becomes Transcendence.Enhanced twice, Beneficent Lotus becomes Divine Spear.Enhanced 3 times, Beneficent Lotus becomes Fulgurant Leap.When using Divine Spear or Fulgurant Leap, starting from the fourth hit, 1 stack of Outroar is gained before every hit. Each stack of Outroar increases Dan Heng • Imbibitor Lunae's CRIT DMG by 6%, for a max of 4 stacks. These stacks last until the end of his turn.",
      ultimateicon: "imageSkills/ImbibitorLunaeUltimate.png",
      ultimatename: "Azure's Aqua Ablutes All",
      ultimatedetail: "Uses a 3-hit attack and deals Imaginary DMG equal to 180% of Dan Heng • Imbibitor Lunae's ATK to a single enemy target. At the same time, deals Imaginary DMG equal to 84% of Dan Heng • Imbibitor Lunae's ATK to adjacent targets. Then, obtains 2 Squama Sacrosancta.It's possible to hold up to 3 Squama Sacrosancta, which can be used to offset the consumption of Dan Heng • Imbibitor Lunae's skill points. Consuming Squama Sacrosancta is considered equivalent to consuming skill points.",
      talenticon: "imageSkills/ImbibitorLunaeTalent.png",
      talentname: "Righteous Heart",
      talentdetail: "After each hit dealt during an attack, Dan Heng • Imbibitor Lunae gains 1 stack of Righteous Heart, increasing his DMG by 5%. This effect can stack up to 6 time(s), lasting until the end of his turn.",
      techniqueicon: "imageSkills/ImbibitorLunaeTechnique.png",
      techniquename: "Heaven-Quelling Prismadrakon",
      techniquedetail: "After using his Technique, Dan Heng • Imbibitor Lunae enters the Leaping Dragon state for 20 seconds. While in the Leaping Dragon state, using his attack enables him to move forward rapidly for a set distance, attacking all enemies he touches and blocking all incoming attacks. After entering combat via attacking enemies in the Leaping Dragon state, Dan Heng • Imbibitor Lunae deals Imaginary DMG equal to 120% of his ATK to all enemies, and gains 1 Squama Sacrosancta.",
      eidolon1icon: "imageEidolon/ImbibitorLunaeEidolon1.png",
      eidolon1name: "Tethered to Sky",
      eidolon1detail: "Increases the stackable Righteous Heart count by 4, and gains 1 extra stack of Righteous Heart for each hit during an attack.",
      eidolon2icon: "imageEidolon/ImbibitorLunaeEidolon2.png",
      eidolon2name: "Imperium On Cloud Nine",
      eidolon2detail: "After using his Ultimate, Dan Heng • Imbibitor Lunae's action is Advanced Forward by 100% and gains 1 extra Squama Sacrosancta.",
      eidolon3icon: "imageEidolon/ImbibitorLunaeEidolon3.png",
      eidolon3name: "Clothed in Clouds",
      eidolon3detail: "Skill Lv. +2, up to a maximum of Lv. 15. Basic ATK Lv. +1, up to a maximum of Lv. 10.",
      eidolon4icon: "imageEidolon/ImbibitorLunaeEidolon4.png",
      eidolon4name: "Zephyr's Bliss",
      eidolon4detail: "The buff effect granted by Outroar lasts until the end of this character's next turn.",
      eidolon5icon: "imageEidolon/ImbibitorLunaeEidolon5.png",
      eidolon5name: "Fall is the Pride",
      eidolon5detail: "Ultimate Lv. +2, up to a maximum of Lv. 15. Talent ATK Lv. +2, up to a maximum of Lv. 15.",
      eidolon6icon: "imageEidolon/ImbibitorLunaeEidolon6.png",
      eidolon6name: "Reign, Returned",
      eidolon6detail: "After any other ally uses their Ultimate, the Imaginary RES PEN of Dan Heng • Imbibitor Lunae's next Fulgurant Leap attack increases by 20%. This effect can stack up to 3 time(s).",
      totalStats1: "Imaginary DMG +22.4%",
      totalStats2: "CRIT Rate +12%",
      totalStats3: "Max HP +10%",
      
      ascension2icon: "imageTraces/ImbibitorLunaeAscension2.png",
      ascension2name: "Star Veil",
      ascension2detail: "At the start of the battle, immediately regenerates 15 Energy.",
      ascension4icon: "imageTraces/ImbibitorLunaeAscension4.png",
      ascension4name: "Aqua Reign",
      ascension4detail: "Increases the chance to resist Crowd Control debuffs by 35%.",
      ascension6icon: "imageTraces/ImbibitorLunaeAscension6.png",
      ascension6name: "Jolt Anew",
      ascension6detail: "This character's CRIT DMG increases by 24% when dealing DMG to enemy targets with Imaginary Weakness.",
      
      hpcharacters: 1241,
      atkcharacters: 698,
      defcharacters: 363,
      speedcharacters: 102,
      tauntcharacters: 125,
      color: Colors.amber
      ),
  //2
       HSRCH(
      id: 2,
      namecharacters: "Kafka",
      charactersRarity: 5,
      imgcharacters: "imagecharacters/kafka.png",
      combatypesimg: "icongame/Lightning.png",
      combatypesname: "Lightning",
      pathcharactersimg: "icongame/TheNihility.png",
      pathcharactersname: "TheNihility",
      Factions: "Stellaron Hunters",
      upgradematerials1img: "imageUpgradeMaterials/ObsidianofDread.png",
      upgradematerials2img: "imageUpgradeMaterials/RegretofInfiniteOchema.png",
      upgradematerials3img: "imageUpgradeMaterials/ShapeShiftersLightningStaff.png",
      upgradematerials4img: "imageUpgradeMaterials/ThiefInstinct.png",
      upgradematerials1name: "Obsidian of Dread",
      upgradematerials2name: "Regret of Infinite Ochema",
      upgradematerials3name: "Lightning Staff",
      upgradematerials4name: "Thief's Instinct",
      basicatkicon: "imageSkills/kafkaBasicATK.png",
      basicatkname: "Midnight Tumult",
      basicatkdetail: "Deals Lightning DMG equal to 50% of Kafka's ATK to a single enemy.",
      skillicon: "imageSkills/kafkaSkill.png",
      skillname: "Caressing Moonlight",
      skilldetail: "Deals Lightning DMG equal to 80% of Kafka's ATK to a target enemy and Lightning DMG equal to 30% of Kafka's ATK to enemies adjacent to it. If the target enemy is currently receiving DoT, all DoTs currently placed on that enemy immediately produce DMG equal to 60% of their original DMG.",
      ultimateicon: "imageSkills/kafkaUltimate.png",
      ultimatename: "Twilight Trill",
      ultimatedetail: "Deals Lightning DMG equal to 48% of Kafka's ATK to all enemies, with a 100% base chance for enemies hit to become Shocked and immediately take DMG equal to 80% of the DoT. Shock lasts for 2 turn(s).While Shocked, enemies receive Lightning DoT equal to 116% of Kafka's ATK at the beginning of each turn.",
      talenticon: "imageSkills/kafkaTalent.png",
      talentname: "Gentle but Cruel",
      talentdetail: "After an ally of Kafka's uses Basic ATK on an enemy target, Kafka immediately launches 1 follow-up attack and deals Lightning DMG equal to 42% of her ATK to that target, with a 100% base chance to inflict Shock equivalent to that applied by her Ultimate to the attacked enemy target for 2 turns. This effect can only be triggered 1 time per turn.",
      techniqueicon: "imageSkills/kafkaTechnique.png",
      techniquename: "Mercy Is Not Forgiveness",
      techniquedetail: "Immediately attacks all enemies within a set range. After entering battle, deals Lightning DMG equal to 50% of Kafka's ATK to all enemies, with a 100% base chance to inflict Shock equivalent to that applied by her Ultimate on every enemy target for 2 turn(s).",
      eidolon1icon: "imageEidolon/kafkaEidolon1.png",
      eidolon1name: "Da Capo",
      eidolon1detail: "When the Talent triggers a follow-up attack, there is a 100% base chance to increase the DoT received by the target by 30% for 2 turn(s).",
      eidolon2icon: "imageEidolon/kafkaEidolon2.png",
      eidolon2name: "Fortississimo",
      eidolon2detail: "While Kafka is on the field, DoT dealt by all allies increases by 25%.",
      eidolon3icon: "imageEidolon/kafkaEidolon3.png",
      eidolon3name: "Capriccio",
      eidolon3detail: "Skill Lv. +2, up to a maximum of Lv. 15. Basic ATK Lv. +1, up to a maximum of Lv. 10.",
      eidolon4icon: "imageEidolon/kafkaEidolon4.png",
      eidolon4name: "Recitativo",
      eidolon4detail: "When an enemy target takes DMG from the Shock status inflicted by Kafka, Kafka additionally regenerates 2 Energy.",
      eidolon5icon: "imageEidolon/kafkaEidolon5.png",
      eidolon5name: "Doloroso",
      eidolon5detail: "Ultimate Lv. +2, up to a maximum of Lv. 15. Talent ATK Lv. +2, up to a maximum of Lv. 15.",
      eidolon6icon: "imageEidolon/kafkaEidolon6.png",
      eidolon6name: "Leggiero",
      eidolon6detail: "The DMG multiplier for Shock DMG dealt by Ultimate, Technique, or the follow-up attack triggered by Talent increases by 156%, and extends the duration of Shock on the enemy target by 1 turn(s).",
      totalStats1: "ATK +28%",
      totalStats2: "Effect Hit Rate +18%",
      totalStats3: "Max HP +10%",
      
      ascension2icon: "imageTraces/kafkaAscension2.png",
      ascension2name: "Torture",
      ascension2detail: "When the Ultimate is used, enemy targets will now receive DMG immediately from all currently applied DoT sources instead of just receiving DMG immediately from the currently applied Shock state.",
      ascension4icon: "imageTraces/kafkaAscension4.png",
      ascension4name: "Plunder",
      ascension4detail: "If an enemy is defeated while Shocked, Kafka additionally regenerates 5 Energy.",
      ascension6icon: "imageTraces/kafkaAscension6.png",
      ascension6name: "Thorns",
      ascension6detail: "The base chance for Ultimate, Technique, or the follow-up attack triggered by the Talent to inflict Shock increases by 30%.",
      
      hpcharacters: 1086,
      atkcharacters: 679,
      defcharacters: 458,
      speedcharacters: 100,
      tauntcharacters: 100,
      color: Colors.amber
      ),
 //3
      HSRCH(
      id: 3,
      namecharacters: "Blade",
      charactersRarity: 5,
      imgcharacters: "imagecharacters/Blade.png",
      combatypesimg: "icongame/wind.png",
      combatypesname: "Wind",
      pathcharactersimg: "icongame/the_destruction_sm.png",
      pathcharactersname: "Destruction",
      Factions: "	Stellaron Hunters",

      upgradematerials1img: "imageUpgradeMaterials/Immortal Scionette.png",
      upgradematerials2img: "imageUpgradeMaterials/RegretofInfiniteOchema.png",
      upgradematerials3img: "imageUpgradeMaterials/Shattered Blade.png",
      upgradematerials4img: "imageUpgradeMaterials/Suppressing Edict.png",
      upgradematerials1name: "Immortal Scionette",
      upgradematerials2name: "Regret of Infinite Ochema",
      upgradematerials3name: "Shattered Blade",
      upgradematerials4name: "Suppressing Edict",

      basicatkicon: "imageSkills/BladeBasicATK.png",
      basicatkname: "Shard Sword",
      basicatkdetail: "Single Target Deals 50% of Blade's ATK as Wind DMG to a target enemy. Blast Consumes HP equal to 10% of Blade's Max HP and deals Wind DMG equal to the sum of 20% of his ATK and 50% of his Max HP to a single enemy. In addition, deals Wind DMG equal to the sum of 8% of Blade's ATK and 20% of his Max HP to adjacent targets. If Blade's current HP is insufficient, his HP will be reduced to 1 when using Forest of Swords. Forest of Swords cannot regenerate Skill Points.",
      skillicon: "imageSkills/BladeSkill.png",
      skillname: "Hellscape",
      skilldetail: "Consumes HP equal to 30% of Blade's Max HP to enter the Hellscape state. When Hellscape is active, his Skill cannot be used, his DMG dealt increases by 12%, and his Basic ATK Shard Sword is enhanced to Forest of Swords for 3 turn(s). If Blade's current HP is insufficient, his HP will be reduced to 1 when he uses his Skill. This Skill does not regenerate Energy. Using this Skill does not end the current turn.",
      ultimateicon: "imageSkills/BladeUltimate.png",
      ultimatename: "Death Sentence",
      ultimatedetail: "Sets Blade's current HP to 50% of his Max HP and deals to a single enemy Wind DMG equal to the sum of 24% of his ATK, 60% of his Max HP, and 60% of the total HP he has lost in the current battle. At the same time, deals Wind DMG to adjacent targets equal to the sum of 9.6% of his ATK, 24% of his Max HP, and 24% of the total HP he has lost in the current battle. The total HP Blade has lost in the current battle is capped at 90% of his Max HP. This value will be reset and re-accumulated after his Ultimate has been used.",
      talenticon: "imageSkills/BladeTalent.png",
      talentname: "Shuhu's Gift",
      talentdetail: "When Blade sustains DMG or consumes his HP, he gains 1 stack of Charge, stacking up to 5 times. A max of 1 Charge stack can be gained every time he is attacked. When Charge stack reaches maximum, immediately launches a follow-up attack on all enemies, dealing Wind DMG equal to 22% of Blade's ATK plus 55% of his Max HP. At the same time, restores Blade's HP by 25% of his Max HP. After the follow-up attack, all Charges are consumed.",
      techniqueicon: "imageSkills/BladeTechnique.png",
      techniquename: "Karma Wind",
      techniquedetail: "Immediately attacks the enemy. After entering combat, consumes 20% of Blade's Max HP while dealing Wind DMG equal to 40% of his Max HP to all enemies. If Blade's current HP is insufficient, his HP will be reduced to 1 when this Technique is used.",
      
      eidolon1icon: "imageEidolon/BladeEidolon1.png",
      eidolon1name: "Blade Cuts the Deepest in Hell",
      eidolon1detail: "Blade's Ultimate deals additionally increased DMG to a single enemy target, with the increased amount equal to 150% of Blade's total HP loss in the current battle. The total HP Blade has lost in the current battle is capped at 90% of his Max HP. This value will be reset and re-accumulated after his Ultimate has been used.",
      eidolon2icon: "imageEidolon/BladeEidolon2.png",
      eidolon2name: "Ten Thousand Sorrows From One Broken Dream",
      eidolon2detail: "When Blade is in the Hellscape state, his CRIT Rate increases by 15%.",
      eidolon3icon: "imageEidolon/BladeEidolon3.png",
      eidolon3name: "Hardened Blade Bleeds Coldest Shade",
      eidolon3detail: "Ultimate Lv. +2, up to a maximum of Lv. 15. Talent Lv. +2, up to a maximum of Lv. 15.",
      eidolon4icon: "imageEidolon/BladeEidolon4.png",
      eidolon4name: "Rejected by Death, Infected With Life",
      eidolon4detail: "When Blade's current HP drops to 50% or lower of his Max HP, increases his Max HP by 20%. Stacks up to 2 time(s).",
      eidolon5icon: "imageEidolon/BladeEidolon5.png",
      eidolon5name: "Death By Ten Lords' Gaze",
      eidolon5detail: "Skill Lv. +2, up to a maximum of Lv. 15. Basic ATK Lv. +1, up to a maximum of Lv. 10.",
      eidolon6icon: "imageEidolon/BladeEidolon6.png",
      eidolon6name: "Reborn Into an Empty Husk",
      eidolon6detail: "The maximum number of Charge stacks is reduced to 4. The DMG of the follow-up attack triggered by Blade's Talent additionally increases by 50% of his Max HP.",
      
      totalStats1: "Max HP% +28%",
      totalStats2: "CRIT Rate +12%",
      totalStats3: "Effect RES +10%",
      
      ascension2icon: "imageTraces/BladeAscension2.png",
      ascension2name: "Vita Infinita",
      ascension2detail: "When Blade's current HP is at 50% of Max HP or lower, Incoming Healing increases by 20%.",
      ascension4icon: "imageTraces/BladeAscension4.png",
      ascension4name: "Neverending Deaths",
      ascension4detail: "If Blade hits a Weakness Broken enemy after using Forest of Swords, he will restore HP equal to 5% of his Max HP plus 100.",
      ascension6icon: "imageTraces/BladeAscension6.png",
      ascension6name: "Cyclone of Destruction",
      ascension6detail: "DMG dealt by Talent's follow-up attack increases by 20%.",
      
      hpcharacters: 1358,
      atkcharacters: 543,
      defcharacters: 485,
      speedcharacters: 97,
      tauntcharacters: 125,
      color: Colors.amber
      ),
//4
      HSRCH(
      id: 4,
      namecharacters: "Luocha",
      charactersRarity: 5,
      imgcharacters: "imagecharacters/Luocha.png",
      combatypesimg: "icongame/wind.png",
      combatypesname: "Wind",
      pathcharactersimg: "icongame/the_destruction_sm.png",
      pathcharactersname: "Destruction",
      Factions: "	Stellaron Hunters",

      upgradematerials1img: "imageUpgradeMaterials/Immortal Scionette.png",
      upgradematerials2img: "imageUpgradeMaterials/RegretofInfiniteOchema.png",
      upgradematerials3img: "imageUpgradeMaterials/Shattered Blade.png",
      upgradematerials4img: "imageUpgradeMaterials/Suppressing Edict.png",
      upgradematerials1name: "Immortal Scionette",
      upgradematerials2name: "Regret of Infinite Ochema",
      upgradematerials3name: "Shattered Blade",
      upgradematerials4name: "Suppressing Edict",

      basicatkicon: "imageSkills/BladeBasicATK.png",
      basicatkname: "Shard Sword",
      basicatkdetail: "Single Target Deals 50% of Blade's ATK as Wind DMG to a target enemy. Blast Consumes HP equal to 10% of Blade's Max HP and deals Wind DMG equal to the sum of 20% of his ATK and 50% of his Max HP to a single enemy. In addition, deals Wind DMG equal to the sum of 8% of Blade's ATK and 20% of his Max HP to adjacent targets. If Blade's current HP is insufficient, his HP will be reduced to 1 when using Forest of Swords. Forest of Swords cannot regenerate Skill Points.",
      skillicon: "imageSkills/BladeSkill.png",
      skillname: "Hellscape",
      skilldetail: "Consumes HP equal to 30% of Blade's Max HP to enter the Hellscape state. When Hellscape is active, his Skill cannot be used, his DMG dealt increases by 12%, and his Basic ATK Shard Sword is enhanced to Forest of Swords for 3 turn(s). If Blade's current HP is insufficient, his HP will be reduced to 1 when he uses his Skill. This Skill does not regenerate Energy. Using this Skill does not end the current turn.",
      ultimateicon: "imageSkills/BladeUltimate.png",
      ultimatename: "Death Sentence",
      ultimatedetail: "Sets Blade's current HP to 50% of his Max HP and deals to a single enemy Wind DMG equal to the sum of 24% of his ATK, 60% of his Max HP, and 60% of the total HP he has lost in the current battle. At the same time, deals Wind DMG to adjacent targets equal to the sum of 9.6% of his ATK, 24% of his Max HP, and 24% of the total HP he has lost in the current battle. The total HP Blade has lost in the current battle is capped at 90% of his Max HP. This value will be reset and re-accumulated after his Ultimate has been used.",
      talenticon: "imageSkills/BladeTalent.png",
      talentname: "Shuhu's Gift",
      talentdetail: "When Blade sustains DMG or consumes his HP, he gains 1 stack of Charge, stacking up to 5 times. A max of 1 Charge stack can be gained every time he is attacked. When Charge stack reaches maximum, immediately launches a follow-up attack on all enemies, dealing Wind DMG equal to 22% of Blade's ATK plus 55% of his Max HP. At the same time, restores Blade's HP by 25% of his Max HP. After the follow-up attack, all Charges are consumed.",
      techniqueicon: "imageSkills/BladeTechnique.png",
      techniquename: "Karma Wind",
      techniquedetail: "Immediately attacks the enemy. After entering combat, consumes 20% of Blade's Max HP while dealing Wind DMG equal to 40% of his Max HP to all enemies. If Blade's current HP is insufficient, his HP will be reduced to 1 when this Technique is used.",
      
      eidolon1icon: "imageEidolon/BladeEidolon1.png",
      eidolon1name: "Blade Cuts the Deepest in Hell",
      eidolon1detail: "Blade's Ultimate deals additionally increased DMG to a single enemy target, with the increased amount equal to 150% of Blade's total HP loss in the current battle. The total HP Blade has lost in the current battle is capped at 90% of his Max HP. This value will be reset and re-accumulated after his Ultimate has been used.",
      eidolon2icon: "imageEidolon/BladeEidolon2.png",
      eidolon2name: "Ten Thousand Sorrows From One Broken Dream",
      eidolon2detail: "When Blade is in the Hellscape state, his CRIT Rate increases by 15%.",
      eidolon3icon: "imageEidolon/BladeEidolon3.png",
      eidolon3name: "Hardened Blade Bleeds Coldest Shade",
      eidolon3detail: "Ultimate Lv. +2, up to a maximum of Lv. 15. Talent Lv. +2, up to a maximum of Lv. 15.",
      eidolon4icon: "imageEidolon/BladeEidolon4.png",
      eidolon4name: "Rejected by Death, Infected With Life",
      eidolon4detail: "When Blade's current HP drops to 50% or lower of his Max HP, increases his Max HP by 20%. Stacks up to 2 time(s).",
      eidolon5icon: "imageEidolon/BladeEidolon5.png",
      eidolon5name: "Death By Ten Lords' Gaze",
      eidolon5detail: "Skill Lv. +2, up to a maximum of Lv. 15. Basic ATK Lv. +1, up to a maximum of Lv. 10.",
      eidolon6icon: "imageEidolon/BladeEidolon6.png",
      eidolon6name: "Reborn Into an Empty Husk",
      eidolon6detail: "The maximum number of Charge stacks is reduced to 4. The DMG of the follow-up attack triggered by Blade's Talent additionally increases by 50% of his Max HP.",
      
      totalStats1: "Max HP% +28%",
      totalStats2: "CRIT Rate +12%",
      totalStats3: "Effect RES +10%",
      
      ascension2icon: "imageTraces/BladeAscension2.png",
      ascension2name: "Vita Infinita",
      ascension2detail: "When Blade's current HP is at 50% of Max HP or lower, Incoming Healing increases by 20%.",
      ascension4icon: "imageTraces/BladeAscension4.png",
      ascension4name: "Neverending Deaths",
      ascension4detail: "If Blade hits a Weakness Broken enemy after using Forest of Swords, he will restore HP equal to 5% of his Max HP plus 100.",
      ascension6icon: "imageTraces/BladeAscension6.png",
      ascension6name: "Cyclone of Destruction",
      ascension6detail: "DMG dealt by Talent's follow-up attack increases by 20%.",
      
      hpcharacters: 1358,
      atkcharacters: 543,
      defcharacters: 485,
      speedcharacters: 97,
      tauntcharacters: 125,
      color: Colors.amber
      ),
//5
        HSRCH(
      id: 5,
      namecharacters: "Silver Wolf",
      charactersRarity: 5,
      imgcharacters: "imagecharacters/Silver Wolf.png",
      combatypesimg: "icongame/Lightning.png",
      combatypesname: "Lightning",
      pathcharactersimg: "icongame/TheNihility.png",
      pathcharactersname: "TheNihility",
      Factions: "Stellaron Hunters",
      upgradematerials1img: "imageUpgradeMaterials/ObsidianofDread.png",
      upgradematerials2img: "imageUpgradeMaterials/RegretofInfiniteOchema.png",
      upgradematerials3img: "imageUpgradeMaterials/ShapeShiftersLightningStaff.png",
      upgradematerials4img: "imageUpgradeMaterials/ThiefInstinct.png",
      upgradematerials1name: "Obsidian of Dread",
      upgradematerials2name: "Regret of Infinite Ochema",
      upgradematerials3name: "Lightning Staff",
      upgradematerials4name: "Thief's Instinct",
      basicatkicon: "imageSkills/kafkaBasicATK.png",
      basicatkname: "Midnight Tumult",
      basicatkdetail: "Deals Lightning DMG equal to 50% of Kafka's ATK to a single enemy.",
      skillicon: "imageSkills/kafkaSkill.png",
      skillname: "Caressing Moonlight",
      skilldetail: "Deals Lightning DMG equal to 80% of Kafka's ATK to a target enemy and Lightning DMG equal to 30% of Kafka's ATK to enemies adjacent to it. If the target enemy is currently receiving DoT, all DoTs currently placed on that enemy immediately produce DMG equal to 60% of their original DMG.",
      ultimateicon: "imageSkills/kafkaUltimate.png",
      ultimatename: "Twilight Trill",
      ultimatedetail: "Deals Lightning DMG equal to 48% of Kafka's ATK to all enemies, with a 100% base chance for enemies hit to become Shocked and immediately take DMG equal to 80% of the DoT. Shock lasts for 2 turn(s).While Shocked, enemies receive Lightning DoT equal to 116% of Kafka's ATK at the beginning of each turn.",
      talenticon: "imageSkills/kafkaTalent.png",
      talentname: "Gentle but Cruel",
      talentdetail: "After an ally of Kafka's uses Basic ATK on an enemy target, Kafka immediately launches 1 follow-up attack and deals Lightning DMG equal to 42% of her ATK to that target, with a 100% base chance to inflict Shock equivalent to that applied by her Ultimate to the attacked enemy target for 2 turns. This effect can only be triggered 1 time per turn.",
      techniqueicon: "imageSkills/kafkaTechnique.png",
      techniquename: "Mercy Is Not Forgiveness",
      techniquedetail: "Immediately attacks all enemies within a set range. After entering battle, deals Lightning DMG equal to 50% of Kafka's ATK to all enemies, with a 100% base chance to inflict Shock equivalent to that applied by her Ultimate on every enemy target for 2 turn(s).",
      eidolon1icon: "imageEidolon/kafkaEidolon1.png",
      eidolon1name: "Da Capo",
      eidolon1detail: "When the Talent triggers a follow-up attack, there is a 100% base chance to increase the DoT received by the target by 30% for 2 turn(s).",
      eidolon2icon: "imageEidolon/kafkaEidolon2.png",
      eidolon2name: "Fortississimo",
      eidolon2detail: "While Kafka is on the field, DoT dealt by all allies increases by 25%.",
      eidolon3icon: "imageEidolon/kafkaEidolon3.png",
      eidolon3name: "Capriccio",
      eidolon3detail: "Skill Lv. +2, up to a maximum of Lv. 15. Basic ATK Lv. +1, up to a maximum of Lv. 10.",
      eidolon4icon: "imageEidolon/kafkaEidolon4.png",
      eidolon4name: "Recitativo",
      eidolon4detail: "When an enemy target takes DMG from the Shock status inflicted by Kafka, Kafka additionally regenerates 2 Energy.",
      eidolon5icon: "imageEidolon/kafkaEidolon5.png",
      eidolon5name: "Doloroso",
      eidolon5detail: "Ultimate Lv. +2, up to a maximum of Lv. 15. Talent ATK Lv. +2, up to a maximum of Lv. 15.",
      eidolon6icon: "imageEidolon/kafkaEidolon6.png",
      eidolon6name: "Leggiero",
      eidolon6detail: "The DMG multiplier for Shock DMG dealt by Ultimate, Technique, or the follow-up attack triggered by Talent increases by 156%, and extends the duration of Shock on the enemy target by 1 turn(s).",
      totalStats1: "ATK +28%",
      totalStats2: "Effect Hit Rate +18%",
      totalStats3: "Max HP +10%",
      
      ascension2icon: "imageTraces/kafkaAscension2.png",
      ascension2name: "Torture",
      ascension2detail: "When the Ultimate is used, enemy targets will now receive DMG immediately from all currently applied DoT sources instead of just receiving DMG immediately from the currently applied Shock state.",
      ascension4icon: "imageTraces/kafkaAscension4.png",
      ascension4name: "Plunder",
      ascension4detail: "If an enemy is defeated while Shocked, Kafka additionally regenerates 5 Energy.",
      ascension6icon: "imageTraces/kafkaAscension6.png",
      ascension6name: "Thorns",
      ascension6detail: "The base chance for Ultimate, Technique, or the follow-up attack triggered by the Talent to inflict Shock increases by 30%.",
      
      hpcharacters: 1086,
      atkcharacters: 679,
      defcharacters: 458,
      speedcharacters: 100,
      tauntcharacters: 100,
      color: Colors.amber
      ),

        HSRCH(
      id: 6,
      namecharacters: "Jing Yuan",
      charactersRarity: 5,
      imgcharacters: "imagecharacters/Jing Yuan.png",
      combatypesimg: "icongame/Lightning.png",
      combatypesname: "Lightning",
      pathcharactersimg: "icongame/TheNihility.png",
      pathcharactersname: "TheNihility",
      Factions: "Stellaron Hunters",
      upgradematerials1img: "imageUpgradeMaterials/ObsidianofDread.png",
      upgradematerials2img: "imageUpgradeMaterials/RegretofInfiniteOchema.png",
      upgradematerials3img: "imageUpgradeMaterials/ShapeShiftersLightningStaff.png",
      upgradematerials4img: "imageUpgradeMaterials/ThiefInstinct.png",
      upgradematerials1name: "Obsidian of Dread",
      upgradematerials2name: "Regret of Infinite Ochema",
      upgradematerials3name: "Lightning Staff",
      upgradematerials4name: "Thief's Instinct",
      basicatkicon: "imageSkills/kafkaBasicATK.png",
      basicatkname: "Midnight Tumult",
      basicatkdetail: "Deals Lightning DMG equal to 50% of Kafka's ATK to a single enemy.",
      skillicon: "imageSkills/kafkaSkill.png",
      skillname: "Caressing Moonlight",
      skilldetail: "Deals Lightning DMG equal to 80% of Kafka's ATK to a target enemy and Lightning DMG equal to 30% of Kafka's ATK to enemies adjacent to it. If the target enemy is currently receiving DoT, all DoTs currently placed on that enemy immediately produce DMG equal to 60% of their original DMG.",
      ultimateicon: "imageSkills/kafkaUltimate.png",
      ultimatename: "Twilight Trill",
      ultimatedetail: "Deals Lightning DMG equal to 48% of Kafka's ATK to all enemies, with a 100% base chance for enemies hit to become Shocked and immediately take DMG equal to 80% of the DoT. Shock lasts for 2 turn(s).While Shocked, enemies receive Lightning DoT equal to 116% of Kafka's ATK at the beginning of each turn.",
      talenticon: "imageSkills/kafkaTalent.png",
      talentname: "Gentle but Cruel",
      talentdetail: "After an ally of Kafka's uses Basic ATK on an enemy target, Kafka immediately launches 1 follow-up attack and deals Lightning DMG equal to 42% of her ATK to that target, with a 100% base chance to inflict Shock equivalent to that applied by her Ultimate to the attacked enemy target for 2 turns. This effect can only be triggered 1 time per turn.",
      techniqueicon: "imageSkills/kafkaTechnique.png",
      techniquename: "Mercy Is Not Forgiveness",
      techniquedetail: "Immediately attacks all enemies within a set range. After entering battle, deals Lightning DMG equal to 50% of Kafka's ATK to all enemies, with a 100% base chance to inflict Shock equivalent to that applied by her Ultimate on every enemy target for 2 turn(s).",
      eidolon1icon: "imageEidolon/kafkaEidolon1.png",
      eidolon1name: "Da Capo",
      eidolon1detail: "When the Talent triggers a follow-up attack, there is a 100% base chance to increase the DoT received by the target by 30% for 2 turn(s).",
      eidolon2icon: "imageEidolon/kafkaEidolon2.png",
      eidolon2name: "Fortississimo",
      eidolon2detail: "While Kafka is on the field, DoT dealt by all allies increases by 25%.",
      eidolon3icon: "imageEidolon/kafkaEidolon3.png",
      eidolon3name: "Capriccio",
      eidolon3detail: "Skill Lv. +2, up to a maximum of Lv. 15. Basic ATK Lv. +1, up to a maximum of Lv. 10.",
      eidolon4icon: "imageEidolon/kafkaEidolon4.png",
      eidolon4name: "Recitativo",
      eidolon4detail: "When an enemy target takes DMG from the Shock status inflicted by Kafka, Kafka additionally regenerates 2 Energy.",
      eidolon5icon: "imageEidolon/kafkaEidolon5.png",
      eidolon5name: "Doloroso",
      eidolon5detail: "Ultimate Lv. +2, up to a maximum of Lv. 15. Talent ATK Lv. +2, up to a maximum of Lv. 15.",
      eidolon6icon: "imageEidolon/kafkaEidolon6.png",
      eidolon6name: "Leggiero",
      eidolon6detail: "The DMG multiplier for Shock DMG dealt by Ultimate, Technique, or the follow-up attack triggered by Talent increases by 156%, and extends the duration of Shock on the enemy target by 1 turn(s).",
      totalStats1: "ATK +28%",
      totalStats2: "Effect Hit Rate +18%",
      totalStats3: "Max HP +10%",
      
      ascension2icon: "imageTraces/kafkaAscension2.png",
      ascension2name: "Torture",
      ascension2detail: "When the Ultimate is used, enemy targets will now receive DMG immediately from all currently applied DoT sources instead of just receiving DMG immediately from the currently applied Shock state.",
      ascension4icon: "imageTraces/kafkaAscension4.png",
      ascension4name: "Plunder",
      ascension4detail: "If an enemy is defeated while Shocked, Kafka additionally regenerates 5 Energy.",
      ascension6icon: "imageTraces/kafkaAscension6.png",
      ascension6name: "Thorns",
      ascension6detail: "The base chance for Ultimate, Technique, or the follow-up attack triggered by the Talent to inflict Shock increases by 30%.",
      
      hpcharacters: 1086,
      atkcharacters: 679,
      defcharacters: 458,
      speedcharacters: 100,
      tauntcharacters: 100,
      color: Colors.amber
      ),

      HSRCH(
      id: 7,
      namecharacters: "Seele",
      charactersRarity: 5,
      imgcharacters: "imagecharacters/Seele.png",
      combatypesimg: "icongame/Lightning.png",
      combatypesname: "Lightning",
      pathcharactersimg: "icongame/TheNihility.png",
      pathcharactersname: "TheNihility",
      Factions: "Stellaron Hunters",
      upgradematerials1img: "imageUpgradeMaterials/ObsidianofDread.png",
      upgradematerials2img: "imageUpgradeMaterials/RegretofInfiniteOchema.png",
      upgradematerials3img: "imageUpgradeMaterials/ShapeShiftersLightningStaff.png",
      upgradematerials4img: "imageUpgradeMaterials/ThiefInstinct.png",
      upgradematerials1name: "Obsidian of Dread",
      upgradematerials2name: "Regret of Infinite Ochema",
      upgradematerials3name: "Lightning Staff",
      upgradematerials4name: "Thief's Instinct",
      basicatkicon: "imageSkills/kafkaBasicATK.png",
      basicatkname: "Midnight Tumult",
      basicatkdetail: "Deals Lightning DMG equal to 50% of Kafka's ATK to a single enemy.",
      skillicon: "imageSkills/kafkaSkill.png",
      skillname: "Caressing Moonlight",
      skilldetail: "Deals Lightning DMG equal to 80% of Kafka's ATK to a target enemy and Lightning DMG equal to 30% of Kafka's ATK to enemies adjacent to it. If the target enemy is currently receiving DoT, all DoTs currently placed on that enemy immediately produce DMG equal to 60% of their original DMG.",
      ultimateicon: "imageSkills/kafkaUltimate.png",
      ultimatename: "Twilight Trill",
      ultimatedetail: "Deals Lightning DMG equal to 48% of Kafka's ATK to all enemies, with a 100% base chance for enemies hit to become Shocked and immediately take DMG equal to 80% of the DoT. Shock lasts for 2 turn(s).While Shocked, enemies receive Lightning DoT equal to 116% of Kafka's ATK at the beginning of each turn.",
      talenticon: "imageSkills/kafkaTalent.png",
      talentname: "Gentle but Cruel",
      talentdetail: "After an ally of Kafka's uses Basic ATK on an enemy target, Kafka immediately launches 1 follow-up attack and deals Lightning DMG equal to 42% of her ATK to that target, with a 100% base chance to inflict Shock equivalent to that applied by her Ultimate to the attacked enemy target for 2 turns. This effect can only be triggered 1 time per turn.",
      techniqueicon: "imageSkills/kafkaTechnique.png",
      techniquename: "Mercy Is Not Forgiveness",
      techniquedetail: "Immediately attacks all enemies within a set range. After entering battle, deals Lightning DMG equal to 50% of Kafka's ATK to all enemies, with a 100% base chance to inflict Shock equivalent to that applied by her Ultimate on every enemy target for 2 turn(s).",
      eidolon1icon: "imageEidolon/kafkaEidolon1.png",
      eidolon1name: "Da Capo",
      eidolon1detail: "When the Talent triggers a follow-up attack, there is a 100% base chance to increase the DoT received by the target by 30% for 2 turn(s).",
      eidolon2icon: "imageEidolon/kafkaEidolon2.png",
      eidolon2name: "Fortississimo",
      eidolon2detail: "While Kafka is on the field, DoT dealt by all allies increases by 25%.",
      eidolon3icon: "imageEidolon/kafkaEidolon3.png",
      eidolon3name: "Capriccio",
      eidolon3detail: "Skill Lv. +2, up to a maximum of Lv. 15. Basic ATK Lv. +1, up to a maximum of Lv. 10.",
      eidolon4icon: "imageEidolon/kafkaEidolon4.png",
      eidolon4name: "Recitativo",
      eidolon4detail: "When an enemy target takes DMG from the Shock status inflicted by Kafka, Kafka additionally regenerates 2 Energy.",
      eidolon5icon: "imageEidolon/kafkaEidolon5.png",
      eidolon5name: "Doloroso",
      eidolon5detail: "Ultimate Lv. +2, up to a maximum of Lv. 15. Talent ATK Lv. +2, up to a maximum of Lv. 15.",
      eidolon6icon: "imageEidolon/kafkaEidolon6.png",
      eidolon6name: "Leggiero",
      eidolon6detail: "The DMG multiplier for Shock DMG dealt by Ultimate, Technique, or the follow-up attack triggered by Talent increases by 156%, and extends the duration of Shock on the enemy target by 1 turn(s).",
      totalStats1: "ATK +28%",
      totalStats2: "Effect Hit Rate +18%",
      totalStats3: "Max HP +10%",
      
      ascension2icon: "imageTraces/kafkaAscension2.png",
      ascension2name: "Torture",
      ascension2detail: "When the Ultimate is used, enemy targets will now receive DMG immediately from all currently applied DoT sources instead of just receiving DMG immediately from the currently applied Shock state.",
      ascension4icon: "imageTraces/kafkaAscension4.png",
      ascension4name: "Plunder",
      ascension4detail: "If an enemy is defeated while Shocked, Kafka additionally regenerates 5 Energy.",
      ascension6icon: "imageTraces/kafkaAscension6.png",
      ascension6name: "Thorns",
      ascension6detail: "The base chance for Ultimate, Technique, or the follow-up attack triggered by the Talent to inflict Shock increases by 30%.",
      
      hpcharacters: 1086,
      atkcharacters: 679,
      defcharacters: 458,
      speedcharacters: 100,
      tauntcharacters: 100,
      color: Colors.amber
      ),

HSRCH(
      id: 8,
      namecharacters: "March 7th",
      charactersRarity: 4,
      imgcharacters: "imagecharacters/March 7th.png",
      combatypesimg: "icongame/ice.png",
      combatypesname: "Ice",
      Factions: "Herta Space Station",
      pathcharactersimg: "icongame/the_erudition_sm.png",
      pathcharactersname: "Erudition",

      upgradematerials1img: "imageUpgradeMaterials/Extinguished Core.png",
      upgradematerials2img: "imageUpgradeMaterials/Horn of Snow.png",
      upgradematerials3img: "imageUpgradeMaterials/Key of Inspiration.png",
      upgradematerials4img: "imageUpgradeMaterials/Destroyers Final Road.png",
      upgradematerials1name: "Extinguished Core",
      upgradematerials2name: "Horn of Snow",
      upgradematerials3name: "Key of Inspiration",
      upgradematerials4name: "Destroyers Final Road",

      basicatkicon: "imageSkills/hertaBasicATK.png",
      basicatkname: "What Are You Looking At?",
      basicatkdetail: "Deals Ice DMG equal to 50% of Herta's ATK to a single enemy.",
      skillicon: "imageSkills/hertaSkill.png",
      skillname: "One-Time Offer",
      skilldetail: "Deals Ice DMG equal to 50% of Herta's ATK to all enemies. If the enemy's HP percentage is 50% or higher, DMG dealt to this target increases by 20%.",
      ultimateicon: "imageSkills/hertaUltimate.png",
      ultimatename: "It's Magic, I Added Some Magic",
      ultimatedetail: "Deals Ice DMG equal to 120% of Herta's ATK to all enemies.",
      talenticon: "imageSkills/hertaTalent.png",
      talentname: "Fine, I'll Do It Myself",
      talentdetail: "When an ally's attack causes an enemy's HP percentage to fall to 50% or lower, Herta will launch a follow-up attack, dealing Ice DMG equal to 25% of Herta's ATK to all enemies.",
      techniqueicon: "imageSkills/hertaTechnique.png",
      techniquename: "It Can Still Be Optimized",
      techniquedetail: "After using her Technique, Herta's ATK increases by 40% for 3 turn(s) at the beginning of the the next battle.",
      
      eidolon1icon: "imageEidolon/hertaEidolon1.png",
      eidolon1name: "Kick You When You're Down",
      eidolon1detail: "If the enemy's HP percentage is at 50% or less, Herta's Basic ATK deals additional Ice DMG equal to 40% of Herta's ATK.",
      eidolon2icon: "imageEidolon/hertaEidolon2.png",
      eidolon2name: "Keep the Ball Rolling",
      eidolon2detail: "Every time Talent is triggered, this character's CRIT Rate increases by 3%. This effect can stack up to 5 time(s).",
      eidolon3icon: "imageEidolon/hertaEidolon3.png",
      eidolon3name: "That's the Kind of Girl I Am",
      eidolon3detail: "Skill Lv. +2, up to a maximum of Lv. 15. Basic ATK Lv. +1, up to a maximum of Lv. 10.",
      eidolon4icon: "imageEidolon/hertaEidolon4.png",
      eidolon4name: "Hit Where It Hurts",
      eidolon4detail: "When Talent is triggered, DMG increases by 10%.",
      eidolon5icon: "imageEidolon/hertaEidolon5.png",
      eidolon5name: "Cuss Big or Cuss Nothing",
      eidolon5detail: "Ultimate Lv. +2, up to a maximum of Lv. 15. Talent ATK Lv. +2, up to a maximum of Lv. 15.",
      eidolon6icon: "imageEidolon/hertaEidolon6.png",
      eidolon6name: "No One Can Betray Me",
      eidolon6detail: "After using Ultimate, this character's ATK increases by 25% for 1 turn(s).",
      
      totalStats1: "Ice DMG +22.4%",
      totalStats2: "DEF +22.5%",
      totalStats3: "CRIT Rate +6.7%",
      ascension2icon: "imageTraces/hertaAscension2.png",
      ascension2name: "Efficiency",
      ascension2detail: "When Skill is used, the DMG Boost on target enemies increases by an extra 25%.",
      ascension4icon: "imageTraces/hertaAscension4.png",
      ascension4name: "Puppet",
      ascension4detail: "The chance to resist Crowd Control debuffs increases by 35%.",
      ascension6icon: "imageTraces/hertaAscension6.png",
      ascension6name: "Icing",
      ascension6detail: "When Ultimate is used, deals 20% more DMG to Frozen enemies.",
      
      hpcharacters: 952,
      atkcharacters: 582,
      defcharacters: 396,
      speedcharacters: 100,
      tauntcharacters: 75,
      color: Colors.purple
      ),

      HSRCH(
      id: 9,
      namecharacters: "Dan Heng",
      charactersRarity: 4,
      imgcharacters: "imagecharacters/Dan Heng.png",
      combatypesimg: "icongame/ice.png",
      combatypesname: "Ice",
      Factions: "Herta Space Station",
      pathcharactersimg: "icongame/the_erudition_sm.png",
      pathcharactersname: "Erudition",

      upgradematerials1img: "imageUpgradeMaterials/Extinguished Core.png",
      upgradematerials2img: "imageUpgradeMaterials/Horn of Snow.png",
      upgradematerials3img: "imageUpgradeMaterials/Key of Inspiration.png",
      upgradematerials4img: "imageUpgradeMaterials/Destroyers Final Road.png",
      upgradematerials1name: "Extinguished Core",
      upgradematerials2name: "Horn of Snow",
      upgradematerials3name: "Key of Inspiration",
      upgradematerials4name: "Destroyers Final Road",

      basicatkicon: "imageSkills/hertaBasicATK.png",
      basicatkname: "What Are You Looking At?",
      basicatkdetail: "Deals Ice DMG equal to 50% of Herta's ATK to a single enemy.",
      skillicon: "imageSkills/hertaSkill.png",
      skillname: "One-Time Offer",
      skilldetail: "Deals Ice DMG equal to 50% of Herta's ATK to all enemies. If the enemy's HP percentage is 50% or higher, DMG dealt to this target increases by 20%.",
      ultimateicon: "imageSkills/hertaUltimate.png",
      ultimatename: "It's Magic, I Added Some Magic",
      ultimatedetail: "Deals Ice DMG equal to 120% of Herta's ATK to all enemies.",
      talenticon: "imageSkills/hertaTalent.png",
      talentname: "Fine, I'll Do It Myself",
      talentdetail: "When an ally's attack causes an enemy's HP percentage to fall to 50% or lower, Herta will launch a follow-up attack, dealing Ice DMG equal to 25% of Herta's ATK to all enemies.",
      techniqueicon: "imageSkills/hertaTechnique.png",
      techniquename: "It Can Still Be Optimized",
      techniquedetail: "After using her Technique, Herta's ATK increases by 40% for 3 turn(s) at the beginning of the the next battle.",
      
      eidolon1icon: "imageEidolon/hertaEidolon1.png",
      eidolon1name: "Kick You When You're Down",
      eidolon1detail: "If the enemy's HP percentage is at 50% or less, Herta's Basic ATK deals additional Ice DMG equal to 40% of Herta's ATK.",
      eidolon2icon: "imageEidolon/hertaEidolon2.png",
      eidolon2name: "Keep the Ball Rolling",
      eidolon2detail: "Every time Talent is triggered, this character's CRIT Rate increases by 3%. This effect can stack up to 5 time(s).",
      eidolon3icon: "imageEidolon/hertaEidolon3.png",
      eidolon3name: "That's the Kind of Girl I Am",
      eidolon3detail: "Skill Lv. +2, up to a maximum of Lv. 15. Basic ATK Lv. +1, up to a maximum of Lv. 10.",
      eidolon4icon: "imageEidolon/hertaEidolon4.png",
      eidolon4name: "Hit Where It Hurts",
      eidolon4detail: "When Talent is triggered, DMG increases by 10%.",
      eidolon5icon: "imageEidolon/hertaEidolon5.png",
      eidolon5name: "Cuss Big or Cuss Nothing",
      eidolon5detail: "Ultimate Lv. +2, up to a maximum of Lv. 15. Talent ATK Lv. +2, up to a maximum of Lv. 15.",
      eidolon6icon: "imageEidolon/hertaEidolon6.png",
      eidolon6name: "No One Can Betray Me",
      eidolon6detail: "After using Ultimate, this character's ATK increases by 25% for 1 turn(s).",
      
      totalStats1: "Ice DMG +22.4%",
      totalStats2: "DEF +22.5%",
      totalStats3: "CRIT Rate +6.7%",
      ascension2icon: "imageTraces/hertaAscension2.png",
      ascension2name: "Efficiency",
      ascension2detail: "When Skill is used, the DMG Boost on target enemies increases by an extra 25%.",
      ascension4icon: "imageTraces/hertaAscension4.png",
      ascension4name: "Puppet",
      ascension4detail: "The chance to resist Crowd Control debuffs increases by 35%.",
      ascension6icon: "imageTraces/hertaAscension6.png",
      ascension6name: "Icing",
      ascension6detail: "When Ultimate is used, deals 20% more DMG to Frozen enemies.",
      
      hpcharacters: 952,
      atkcharacters: 582,
      defcharacters: 396,
      speedcharacters: 100,
      tauntcharacters: 75,
      color: Colors.purple
      ),

        HSRCH(
      id: 10,
      namecharacters: "Herta",
      charactersRarity: 4,
      imgcharacters: "imagecharacters/herta.png",
      combatypesimg: "icongame/ice.png",
      combatypesname: "Ice",
      Factions: "Herta Space Station",
      pathcharactersimg: "icongame/the_erudition_sm.png",
      pathcharactersname: "Erudition",

      upgradematerials1img: "imageUpgradeMaterials/Extinguished Core.png",
      upgradematerials2img: "imageUpgradeMaterials/Horn of Snow.png",
      upgradematerials3img: "imageUpgradeMaterials/Key of Inspiration.png",
      upgradematerials4img: "imageUpgradeMaterials/Destroyers Final Road.png",
      upgradematerials1name: "Extinguished Core",
      upgradematerials2name: "Horn of Snow",
      upgradematerials3name: "Key of Inspiration",
      upgradematerials4name: "Destroyers Final Road",

      basicatkicon: "imageSkills/hertaBasicATK.png",
      basicatkname: "What Are You Looking At?",
      basicatkdetail: "Deals Ice DMG equal to 50% of Herta's ATK to a single enemy.",
      skillicon: "imageSkills/hertaSkill.png",
      skillname: "One-Time Offer",
      skilldetail: "Deals Ice DMG equal to 50% of Herta's ATK to all enemies. If the enemy's HP percentage is 50% or higher, DMG dealt to this target increases by 20%.",
      ultimateicon: "imageSkills/hertaUltimate.png",
      ultimatename: "It's Magic, I Added Some Magic",
      ultimatedetail: "Deals Ice DMG equal to 120% of Herta's ATK to all enemies.",
      talenticon: "imageSkills/hertaTalent.png",
      talentname: "Fine, I'll Do It Myself",
      talentdetail: "When an ally's attack causes an enemy's HP percentage to fall to 50% or lower, Herta will launch a follow-up attack, dealing Ice DMG equal to 25% of Herta's ATK to all enemies.",
      techniqueicon: "imageSkills/hertaTechnique.png",
      techniquename: "It Can Still Be Optimized",
      techniquedetail: "After using her Technique, Herta's ATK increases by 40% for 3 turn(s) at the beginning of the the next battle.",
      
      eidolon1icon: "imageEidolon/hertaEidolon1.png",
      eidolon1name: "Kick You When You're Down",
      eidolon1detail: "If the enemy's HP percentage is at 50% or less, Herta's Basic ATK deals additional Ice DMG equal to 40% of Herta's ATK.",
      eidolon2icon: "imageEidolon/hertaEidolon2.png",
      eidolon2name: "Keep the Ball Rolling",
      eidolon2detail: "Every time Talent is triggered, this character's CRIT Rate increases by 3%. This effect can stack up to 5 time(s).",
      eidolon3icon: "imageEidolon/hertaEidolon3.png",
      eidolon3name: "That's the Kind of Girl I Am",
      eidolon3detail: "Skill Lv. +2, up to a maximum of Lv. 15. Basic ATK Lv. +1, up to a maximum of Lv. 10.",
      eidolon4icon: "imageEidolon/hertaEidolon4.png",
      eidolon4name: "Hit Where It Hurts",
      eidolon4detail: "When Talent is triggered, DMG increases by 10%.",
      eidolon5icon: "imageEidolon/hertaEidolon5.png",
      eidolon5name: "Cuss Big or Cuss Nothing",
      eidolon5detail: "Ultimate Lv. +2, up to a maximum of Lv. 15. Talent ATK Lv. +2, up to a maximum of Lv. 15.",
      eidolon6icon: "imageEidolon/hertaEidolon6.png",
      eidolon6name: "No One Can Betray Me",
      eidolon6detail: "After using Ultimate, this character's ATK increases by 25% for 1 turn(s).",
      
      totalStats1: "Ice DMG +22.4%",
      totalStats2: "DEF +22.5%",
      totalStats3: "CRIT Rate +6.7%",
      ascension2icon: "imageTraces/hertaAscension2.png",
      ascension2name: "Efficiency",
      ascension2detail: "When Skill is used, the DMG Boost on target enemies increases by an extra 25%.",
      ascension4icon: "imageTraces/hertaAscension4.png",
      ascension4name: "Puppet",
      ascension4detail: "The chance to resist Crowd Control debuffs increases by 35%.",
      ascension6icon: "imageTraces/hertaAscension6.png",
      ascension6name: "Icing",
      ascension6detail: "When Ultimate is used, deals 20% more DMG to Frozen enemies.",
      
      hpcharacters: 952,
      atkcharacters: 582,
      defcharacters: 396,
      speedcharacters: 100,
      tauntcharacters: 75,
      color: Colors.purple
      ),
];